language: cpp
sudo: required
services:
  - docker
dist: trusty

before_install:
  - docker pull peterdavehello/debian-8-shellcheck
  - sudo apt-get install -y shellcheck

jobs:
  include:
    - stage: check
      script:
        - docker run --rm -v $(pwd):/code peterdavehello/debian-8-shellcheck bash -c 'shellcheck /code/*.sh'
    - stage: build
      script:
        - mkdir build
        - cd build
        - cmake ../
        - make
    - stage: test
      script:
        - cat test/post.txt | build/elog-parse "%[id]"
