language: cpp

sudo: required

services:
  - docker

dist: trusty

os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - root-system
      - libroot-io-dev
      - libroot-tree-dev
      - libroot-core-dev
      - libroot-math-mathcore-dev
      - libroot-graf2d-gpad-dev
      - libroot-graf2d-graf-dev
      - libroot-graf2d-postscript-dev
      - libroot-graf3d-g3d-dev
      - libroot-gui-dev
      - libroot-hist-dev
      - libroot-math-matrix-dev
      - libroot-math-physics-dev
      - libroot-net-dev

before_install:
  - docker pull peterdavehello/debian-8-shellcheck
  - docker pull buddaci/cppcheck

jobs:
  include:
    - stage: check
      script:
        - docker run --rm -v $(pwd):/code peterdavehello/debian-8-shellcheck bash -c 'shellcheck /code/*.sh'
        - docker run --rm -v $(pwd):/code buddaci/cppcheck cppcheck /code/src/ /code/include/ /code/test/
    - stage: build
      script:
        - mkdir build
        - cd build
        - export CXX=g++-4.9
        - export ROOTSYS=/usr
        - cmake ../
        - make
        - make test
        - cd ..
        - '[ "$(cat test/post.txt | build/elog-parse "%[id]")" == "1" ]'
        - '[ "$(cat test/post.txt | build/elog-parse "%[Cut 1]")" == "E > 10" ]'
        - '[ "$(cat test/post.txt | build/elog-parse)" == "$(cat test/post.txt)" ]'
        - '[ "$(cat test/post.txt | build/elog-parse "%[Parameter with (parentheses)]")" == "4" ]'
