language: bash

sudo: required

services:
  - docker

dist: trusty

os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - cmake
      - cmake-data
      - make

before_install:
  - docker pull peterdavehello/debian-8-shellcheck

jobs:
  include:
    - stage: check
      script:
        - docker run --rm -v $(pwd):/code peterdavehello/debian-8-shellcheck bash -c 'shellcheck /code/*.sh'
    - stage: build
      script:
        - mkdir build
        - cd build
        - export CC=gcc-4.9
        - export CXX=g++-4.9
        - cmake ../
        - make
        - cd ..
        - cat test/post.txt | build/elog-parse "%[id]"
