language: cpp

sudo: required

services:
  - docker

dist: trusty

os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - root-system

before_install:
  - docker pull peterdavehello/debian-8-shellcheck
  - docker pull buddaci/cppcheck

jobs:
  include:
    - stage: check
      script:
        - docker run --rm -v $(pwd):/code peterdavehello/debian-8-shellcheck bash -c 'shellcheck /code/*.sh'
        - docker run --rm -v $(pwd):/code buddaci/cppcheck cppcheck /code/src/
    - stage: build
      script:
        - mkdir build
        - cd build
        - export CXX=g++-4.9
        - export ROOTSYS=/usr
        - cmake ../
        - make
        - cd ..
        - '[ "$(cat test/post.txt | build/elog-parse "%[id]")" == "1" ]'
        - '[ "$(cat test/post.txt | build/elog-parse "%[Cut 1]")" == "E > 10" ]'
        - '[ "$(cat test/post.txt | build/elog-parse)" == "$(cat test/post.txt)" ]'
        - '[ "$(cat test/post.txt | build/elog-parse "%[Parameter with (parentheses)]")" == "4" ]'
