language: cpp
compiler:
  - clang
  - gcc
sudo: required
services:
  - docker
dist: trusty
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++4.9"

before_install:
  - eval "${MATRIX_EVAL}"
  - docker pull peterdavehello/debian-8-shellcheck

jobs:
  include:
    - stage: check
      script:
        - docker run --rm -v $(pwd):/code peterdavehello/debian-8-shellcheck bash -c 'shellcheck /code/*.sh'
    - stage: build
      script:
        - mkdir build
        - cd build
        - cmake ../
        - make
    - stage: test
      script:
        - cat test/post.txt | build/elog-parse "%[id]"
